
name: scan_file_system

on:
  # pull_request:
  #   types: [opened, reopened]
  workflow_dispatch:
jobs:
  build_and_scan_image:
      name: scan_file_system
      runs-on: ubuntu-latest
      env:
        PROJECT_KEY: "secret-orca-demo"
      steps:
      # checks-out your repository under $GitHub_WORKSPACE, so your workflow can access it.
        - name: Checkout
          uses: actions/checkout@v3
          #with:
          #  fetch-depth: 0
        - name: Scan source code 
          env:
            ORCA_SECURITY_API_TOKEN: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          run: |
            set +e
            apt update && apt install -y curl
            curl -sfL 'https://raw.GitHubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash
            orca-cli -p ${PROJECT_KEY} fs scan ./
